### ISSUE TITLE
Tooltip "Double" opens when triggered

### ISSUE THREAD

**Issue by BlueVajra** [react-component/tooltip#114]
You can see an example on the examples page: http://react-component.github.io/tooltip/examples/onVisibleChange.html

When you click on the "trigger" it render's twice very quickly

Mac Chrome: Version 63.0.3239.132

**Comment by BlueVajra** [comment]
So I tried digging into this issue and found that the base class for the tooltip has an opacity of 0.9. so there is a "flash" of the tooltip when is is made visible and before it gets the `opacity: 0` from `&-zoom-appear`

the simple solution is removing the opacity from the root component and letting the animation control the opacity. I am unsure of any downstream issues with this.

**Comment by moonray** [comment]
Same issue. However, setting opacity to 0 hides the tooltip when it's supposed to be visible, after the animation completes, when a popup container is set.

**Comment by eyaldouwma** [comment]
can you maybe share the code that fixed this issue? i am struggling with this. thanks :)

**Comment by tony** [comment]
@BlueVajra @moonray Hi there!  Can either of you show an example of what you mean?

**Comment by benyaminbeyzaie** [comment]
Please checkout the code and let me know if this PR solves your problem.

**Comment by davidjb** [comment]
Removing the `opacity` from the base tooltip class (e.g. `.rc-tooltip`) solves this issue. However, for folks who can't modify the base CSS directly (use as an NPM module etc), you can either unset the property with:

```css
.rc-tooltip {
  opacity: unset;
}
```
if you're able to define this rule _after_ the base CSS. Alternatively, if you don't know or can't control the ordering of your CSS, then: 

```css
.rc-tooltip-zoom-enter.rc-tooltip-zoom-enter-prepare,
.rc-tooltip-zoom-enter.rc-tooltip-zoom-enter-start,
.rc-tooltip-zoom-appear.rc-tooltip-zoom-appear-start {
  opacity: 0
}
```
will covers all the states where the tooltip flashes and appears ahead of the given animation starting, taking precedence as they're more specific than the base class.
