### ISSUE TITLE
Position of tooltip for zoomed elements is wrong

### ISSUE THREAD

**Issue by lanzz** [react-component/tooltip#87]
When the trigger for a tooltip is within a zoomed element (i.e. styled with `zoom: .85`), the calculation of the alignment of the tooltip element is way off — it looks as if it simply does not take the zoom factor into account and positions the tooltip as if the trigger was not zoomed at all, so it ends up way to the right and below the trigger (for zoom factors < 1). It is very obvious with a smallish trigger element positioned near the right side of a the actual element that has the `zoom` rule.

**Comment by benjycui** [comment]
Could your provide re-producible demo for this?

**Comment by lanzz** [comment]
JSX:
```html
<div className="zoomed">
  <div className="positioned">
    <Tooltip placement="bottom" overlay={<span>Hello World</span>}>
      <div className="trigger">Trigger</div>
    </Tooltip>
  </div>
</div>
```

CSS:
```css
.zoomed {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  zoom: .85;
}

.positioned {
  position: absolute;
  top: 40%;
  left: 40%;
}
```

![screen shot 2017-06-23 at 10 25 39 3](https://user-images.githubusercontent.com/130721/27475823-7846767c-57fe-11e7-804c-b5372d58cfef.png)
